// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbZv-XjZoi_bHHhfxgsF2ri1uPpJhCMhc',
    appId: '1:945124878596:web:173ee40c10eeaec6d04851',
    messagingSenderId: '945124878596',
    projectId: 'medicine-acf45',
    authDomain: 'medicine-acf45.firebaseapp.com',
    storageBucket: 'medicine-acf45.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE5hwmv9zKss92xy3kEv2bzWOoIjyDSMU',
    appId: '1:945124878596:android:3970b669efd9c0a0d04851',
    messagingSenderId: '945124878596',
    projectId: 'medicine-acf45',
    storageBucket: 'medicine-acf45.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbZv-XjZoi_bHHhfxgsF2ri1uPpJhCMhc',
    appId: '1:945124878596:web:d13e0cc68d8fa730d04851',
    messagingSenderId: '945124878596',
    projectId: 'medicine-acf45',
    authDomain: 'medicine-acf45.firebaseapp.com',
    storageBucket: 'medicine-acf45.appspot.com',
  );
}
